name: demo1
no: 2
addr:
  province: sichuan
  city: chengdu
  street: nanjing

leader: true
work: {"title": "engineer", "salary": 10000}
no-op: asds
no_value: ""
max_value: 120
test_value: 12.3
test_name: null
test_title: